//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArcSoftFace
{
    using System;
    using System.Collections.Generic;
    
    public partial class CheckInfo
    {
        public int id { get; set; }
        public string create_time { get; set; }
        public string update_time { get; set; }
        public byte[] feature { get; set; }
        public byte[] iamge { get; set; }
        public string stu_info_id { get; set; }
    }
}
